FROM alpine:latest

RUN  apk update && apk upgrade && \
apk add apache2 && \
apk add apache2-proxy && \
apk add apache2-ssl && \
rm -rf /var/cache/apk/*

CMD  [ "/usr/sbin/httpd", "-D", "FOREGROUND"]

EXPOSE 80
